name: Rubocop

on: 
  push: 
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.6', '2.7', '3.0']

    steps:
      - uses: actions/checkout@v3
      - name: Make executable
        run: git update-index --chmod=+x ./.github/scripts/rubocop_diff.sh
        shell: bash
    steps:
      - uses: actions/checkout@v3
    # - name: Set up Ruby
    # # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # # change this to (see https://github.com/ruby/setup-ruby#versioning):
    # # uses: ruby/setup-ruby@v1
    #   uses: ruby/setup-ruby@0a29871fe2b0200a17a4497bae54fe5df0d973aa # v1.115.3
    #   with:
    #     ruby-version: ${{ matrix.ruby-version }}
      - name: Run Rubocop
        run: ./.github/scripts/rubocop_diff.sh
        shell: bash
      # run: git diff-tree -r --no-commit-id --name-only head origin/develop | xargs rubocop

